[theme]
primaryColor = "#00aeec"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f6f8"
textColor = "#222222"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
